### ISSUE TITLE
load model error

### ISSUE THREAD

**Issue by jiangwqcooler** [geekyutao/RN#3]
Traceback (most recent call last):
  File "eval.py", line 182, in <module>
    model.load_state_dict(pretained_model)
  File "/home/jiangwenqiang/.conda/envs/env3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 763, in load_state_dict
    load(self)
  File "/home/jiangwenqiang/.conda/envs/env3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 761, in load
    load(child, prefix + name + '.')
  File "/home/jiangwenqiang/.conda/envs/env3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 761, in load
    load(child, prefix + name + '.')
  File "/home/jiangwenqiang/.conda/envs/env3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 761, in load
    load(child, prefix + name + '.')
  [Previous line repeated 1 more time]
  File "/home/jiangwenqiang/.conda/envs/env3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 758, in load
    state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
  File "/home/jiangwenqiang/.conda/envs/env3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 685, in _load_from_state_dict
    hook(state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
  File "/home/jiangwenqiang/.conda/envs/env3.6/lib/python3.6/site-packages/torch/nn/utils/spectral_norm.py", line 165, in __call__
    weight_orig = state_dict[prefix + fn.name + '_orig']
KeyError: 'discriminator.module.conv1.0.weight_orig'

**Comment by geekyutao** [comment]
Hi, did you loaded the model correctly? I just tested the eval.py and it worked just fine. 
![image](https://user-images.githubusercontent.com/30614660/78109770-79db0000-742c-11ea-9d13-a7cfc0484a89.png)
